### ISSUE TITLE
Incorporar logo

### ISSUE THREAD

**Issue by maxpipoka** [Noravsky/Misiotronica#4]
https://github.com/Noravsky/Misiotronica/blob/cd971a64c69953232dbd3ecbfa0dee170cdb8b9a/trabajo-integrador/src/Components/NavBar/NavBar.js#L5

Buenas Nora, dentro del componente del navbar podría incorporar el logo de la empresa, para poder reutilizarlo. Y que cada vez que incluya el navbar ya tambien vaya el logo.

**Comment by Noravsky** [comment]
Corregido.
